version: "3"
services:
  ms-disturbance-sandbox:
    container_name: ms-disturbance-sandbox
    image: 'ms-disturbance:sandbox'
    network_mode: bridge
    links:
      - 'ms-disturbance-wiremock-sandbox:wiremock'
      - 'ms-disturbance-db-sandbox:mariadb'
    restart: always
    build:
      context: ../../..
      dockerfile: src/main/docker/Dockerfile
    ports:
      - '9095:8080'
    environment:
      INTEGRATION_MESSAGING_URL: 'http://wiremock:8080/api-messaging'
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_MESSAGING_TOKEN_URI: 'http://wiremock:8080/api-gateway/token'
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_MESSAGING_AUTHORIZATION_GRANT_TYPE: 'client_credentials'
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_MESSAGING_CLIENT_ID: 'the-client-id'
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_MESSAGING_CLIENT_SECRET: 'the-client-secret'
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_MESSAGING_PROVIDER: 'messaging'
      SPRING_PROFILES_ACTIVE: 'sandbox'
      SPRING_JPA_HIBERNATE_DDL_AUTO: 'update'
      SPRING_DATASOURCE_URL: 'jdbc:mariadb://mariadb:3306/dev-disturbance'
      SPRING_DATASOURCE_USERNAME: 'dev-user'
      SPRING_DATASOURCE_PASSWORD: 'dev-password'
    depends_on:
      - ms-disturbance-db-sandbox
      - ms-disturbance-wiremock-sandbox

  ms-disturbance-db-sandbox:
    container_name: ms-disturbance-db-sandbox
    image: 'mariadb:10.6.4'
    network_mode: bridge
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD : 'yes'
      MARIADB_DATABASE: 'dev-disturbance'
      MARIADB_USER: 'dev-user'
      MARIADB_PASSWORD: 'dev-password'
    expose:
      - '3306'

  ms-disturbance-wiremock-sandbox:
    container_name: ms-disturbance-wiremock-sandbox
    image: wiremock/wiremock
    network_mode: bridge
    restart: always
    expose:
      - '8080'
    volumes:
      - $PWD/src/test/resources/wiremock:/home/wiremock
